export const PREINSCRIPCION_VALUES = {
    nombre: '',
    apellido: '',
    edad: '',
    numCel: '',
    nombrePadre: '',
    telefonoPadre: '',
    apellidoPadre: '',
    emailPadre: '',
    nivel: '',
    clases: [],
    dias:[],
    participaMuestra: false,
    estiloMusica: '',
    comentario: '',
    otroInstrumento: '',
    disciplinas6a9: [],
    disciplinas10a15: [],
  }